on:
  push:
    branches: master
    paths:
      - table_of_contents.yml

name: Render README

jobs:
  render:
    name: Render README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rebuild README.md
        run: python rebuild_readme.py

      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit README.md -m 'Rebuild README.md' || echo "No changes to commit"
          git push origin || echo "No changes to commit"